# MD001/heading-increment/header-increment - Heading levels should only increment by one level at a time
MD001: false
# MD033 - Inline HTML
MD033: false
# MD041 - First line in a file should be a top-level heading
MD041: false