backend:
  name: github
  repo: Ingenjorsarbete-For-Klimatet/greenhouse-majorna
  branch: main
  base_url: http://auth.ingenjorsarbeteforklimatet.se

publish_mode: editorial_workflow
media_folder: 'content/images/uploads'

collections:
  - name: 'posts'
    label: 'Post'
    folder: 'content/posts'
    create: true 
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'string' }
      - { label: 'status', name: 'status', widget: 'string' }
