backend:
  name: github
  repo: Ingenjorsarbete-For-Klimatet/greenhouse-majorna
  branch: main
  base_url: http://auth.ingenjorsarbeteforklimatet.se

locale: 'sv'
publish_mode: editorial_workflow

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/posts'
    create: true 
    slug: '{{slug}}'
    media_folder: 'content/data/{{filename}}'
    public_folder: 'data/{{filename}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        required: true
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        date_format: 'YYYY-MM-DD'
        time_format: false
        format: 'YYYY-MM-DD'
        required: true
      - label: 'Author'
        name: 'author'
        widget: 'string'
        required: true
      - label: 'Category'
        name: 'category'
        widget: 'string'
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'string'
        required: true
      - label: 'Status'
        name: 'status'
        widget: 'select'
        required: true
        options: ['published', 'unpublished']
        default: ['published']
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: true
  - name: 'page'
    label: 'Sida'
    folder: 'content/pages'
    create: true 
    slug: '{{slug}}'
    media_folder: 'content/data/{{filename}}'
    public_folder: 'data/{{filename}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        required: true
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        date_format: 'YYYY-MM-DD'
        time_format: false
        format: 'YYYY-MM-DD'
        required: true
      - label: 'Author'
        name: 'author'
        widget: 'string'
        required: true
      - label: 'Type'
        name: 'type'
        widget: 'select'
        required: true
        options: ['page']
        default: ['page']
      - label: 'Status'
        name: 'status'
        widget: 'select'
        required: true
        options: ['published', 'unpublished']
        default: ['published']
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: true