# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Test build

on:
  pull_request:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install mysgen
        run: pip install mysgen==0.4.2
      - name: Build site
        run: python -m mysgen.mysgen && cp -r theme/css/ output/css/ && mv output _site
